Fix typos and grammar mistakes in English and in French
Dysnomia-Studio/extortion-i18n pull request #1
Opened 2022-08-04 15:34 UTC by Bethoth

The main information is in the title. I would also remove all contractions (like "it's" or "which'll") and abbreviations (like "3rd") but the choice is not mine, they can bring some sorts of nuance and style to the speech.

2022-08-04 15:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/Dysnomia-Studio/extortion-i18n?pullRequest=1) <br/>All committers have signed the CLA.

2022-08-10 18:42 UTC, Elanis requested changes
Hello !

Merci beaucoup pour cette relecture très complète des deux langues :) Tu as spot pas mal de petites typo que ni moi ni ma relectrice (en anglais) n'avions vus 😄 

J'ai mis quelques petits commentaires sur les modifications, je te laisse les traiter/y répondre ;)

Merci encore !

2022-08-10 18:42 UTC, Elanis commented on commands/en.json
> -  "csv_builder_complete": "Files build complete",
Ici le s est normal je pense, il y a plusieurs fichiers qui sont build ensemble

2022-08-10 18:42 UTC, Elanis commented on commands/en.json
> +  "csv_builder_complete": "File build complete",
```suggestion
  "csv_builder_complete": "Files build complete",
```

2022-08-10 18:42 UTC, Elanis commented on commands/en.json
> +  "csv_builder_failed": "Error: File build failed",
```suggestion
  "csv_builder_failed": "Error: Files build failed",
```

2022-08-10 18:42 UTC, Elanis commented on commands/fr.json
> +  "help_header": "Commandes disponibles :",
Pas fan du passage au présent ici, j'aime bien l'infinitif. Par contre, rien a redire sur les espaces ou les autres corrections :)

2022-08-10 18:42 UTC, Elanis commented on commands/fr.json
> +  "help_cmd_exit": "exit : Se déconnecte du server courant (ou retourne au menu principal). Utilisation : <1>exit</1>",
```suggestion
  "help_cmd_exit": "exit : Se déconnecter du serveur courant (ou retourner au menu principal). Utilisation : <1>exit</1>",
```

2022-08-10 18:42 UTC, Elanis commented on files/fr/notes_08.json
> +  "description": "Je pensais être tranquille, cela faisait 2 jours que je n’avais pas eu de nouvelles du chanteur, mais il m’a recontactée pour un autre de ses “jobs”. À la vue de ses phrases, je cro
"Au vu de" est une expression valide, je viens re-verifier, et je trouve que ca sonne mieux

```suggestion
  "description": "Je pensais être tranquille, cela faisait 2 jours que je n’avais pas eu de nouvelles du chanteur, mais il m’a recontactée pour un autre de ses “jobs”. Au vu de ses phrases, je crois qu’il a lu mes notes précédentes, il faut que je trouve un moyen de les cacher, mon PC n’est plus assez sécurisé."
```

2022-08-10 18:42 UTC, Elanis commented on scripts/en.json
> +  "8_2a_condamn-1-0": "You chose to condemn the blackmailer.",
Les deux sont valides pour le coup, mais on peut garder ta version

2022-08-10 18:42 UTC, Elanis commented on scripts/fr.json
> -  "2_0_merge_end-0-1": "Comme vous pourrez le voir, il contient différents comptes qui ont pu être découverts par un groupe de hackers. Le soucis, c’est que seuls certains de ces comptes nous intéres
J'ai un doute pour cette correction là

2022-08-10 18:42 UTC, Elanis commented on scripts/fr.json
> +  "7_0_first_server-0-0": "L’adresse que j’ai trouvéé, c’est ",
```suggestion
  "7_0_first_server-0-0": "L’adresse que j’ai trouvée, c’est ",
```

2022-08-10 19:02 UTC, Bethoth commented on commands/en.json
> -  "csv_builder_complete": "Files build complete",
En fait ça dépend : soit on considère qu'on build les fichiers ensemble donc il y aurait un s, soit on considère qu'un construit un fichier donc pas de s.

2022-08-10 19:04 UTC, Elanis commented on commands/en.json
> -  "csv_builder_complete": "Files build complete",
Ouaip, j'avais plus la première version en tête

2022-08-10 19:04 UTC, Bethoth commented on commands/fr.json
> +  "help_header": "Commandes disponibles :",
J'avais fait ça surtout dans un but d'uniformisation et je trouvais qu'en général, le présent sonnait mieux.

2022-08-10 19:12 UTC, Bethoth commented on scripts/en.json
> +  "8_2a_condamn-1-0": "You chose to condemn the blackmailer.",
Je savais pas que "choosed" était valide mais ça sonne moins bien je trouve.

2022-08-10 19:19 UTC, Bethoth commented on scripts/fr.json
> -  "2_0_merge_end-0-1": "Comme vous pourrez le voir, il contient différents comptes qui ont pu être découverts par un groupe de hackers. Le soucis, c’est que seuls certains de ces comptes nous intéres
J'étais absolument sûr qu'il y avait une différence entre "lesquels" et "les quels" mais après vérification sur différents forums linguistiques, il semblerait qu'on utilise en fait "lesquels" dans tous les cas.

2022-08-10 19:21 UTC, Bethoth commented on commands/en.json
> -  "csv_builder_complete": "Files build complete",
Du coup il faut faire un choix, je te laisse décider.

2022-08-10 19:22 UTC, Elanis commented on commands/en.json
> -  "csv_builder_complete": "Files build complete",
Je prefere garder files ici pour le coup

2022-08-10 19:23 UTC, Elanis commented on commands/fr.json
> +  "help_header": "Commandes disponibles :",
En effet, il y a une mélange, j'avais pas remarqué, on va laisser au présent je pense, t'as raison

2022-08-10 19:34 UTC, Bethoth commented on commands/fr.json
> +  "help_header": "Commandes disponibles :",
Du coup j'ai juste à cliquer "resolve conversation" ?

2022-08-10 19:34 UTC, Elanis commented on commands/fr.json
> +  "help_header": "Commandes disponibles :",
Done !

2022-08-10 19:38 UTC, Bethoth commented on scripts/fr.json
> -  "2_0_merge_end-0-1": "Comme vous pourrez le voir, il contient différents comptes qui ont pu être découverts par un groupe de hackers. Le soucis, c’est que seuls certains de ces comptes nous intéres
J'ai rechangé du coup.

2022-08-10 19:39 UTC, Elanis commented on scripts/fr.json
> -  "2_0_merge_end-0-1": "Comme vous pourrez le voir, il contient différents comptes qui ont pu être découverts par un groupe de hackers. Le soucis, c’est que seuls certains de ces comptes nous intéres
Yes, super merci :)

2022-08-10 19:40 UTC, Elanis approved these changes

2022-08-10 19:41 UTC, Elanis commented
Merci énormément pour ton temps et ton aide ! J'intégrerai tout ca dans la prochaine mise à jour :)

2022-08-10 19:41 UTC, merged

2022-08-10 20:30 UTC, Bethoth commented
C'était avec plaisir. J'avais toujours eu envie de contribuer à un gros projet, c'est désormais chose faite :)

Il se pourrait également que je me lance dans une traduction vers une nouvelle langue mais je suis pas sûr, faut encore que je vois si c'est faisable. Je te tiendrai au courant.